controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = imagesExt.CreateProjectileAtAngleFromSprite(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        .......22...22......
        ......2322.2222.....
        ......232222222.....
        ......222222222.....
        .......22222b2......
        ........222b2.......
        .........222........
        ..........2.........
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        `, mySprite, 100)
})
let projectile: Sprite = null
let mySprite: Sprite = null
scene.setBackgroundImage(storySprites.world)
let myImage = assets.image`box`
mySprite = sprites.create(myImage, SpriteKind.Player)
mySprite.setBounceOnWall(false)
mySprite.setStayInScreen(true)
mySprite.fx = 10
mySprite.fy = 10
imagesExt.moveSpriteAngular(
mySprite,
assets.image`box`,
-90,
-90,
100,
10,
10,
45
)
